name: Daily Resmigazete Scraper

on:
  schedule:
    # 07:00 UTC = 10:00 Istanbul time
    - cron: '0 7 * * *'
  workflow_dispatch:   # allow manual run too

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests beautifulsoup4 openpyxl azure-storage-blob

      - name: Run scraper
        run: python function_app.py

      - name: Upload JSON to Azure Blob
        uses: azure/storage-blob-upload-action@v1
        with:
          connection_string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
          container_name: resmigazete
          source: "*.json"
